# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: En-ti-tled London
email: entitled@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  We provide high end clothing for both Men and Women. Located in London, Ontario
  we strive to provide excellent customer service and a wonderful shopping experience
  to our valued customers. We specialize in high end pieces to accompany our awesome basics!

#baseurl: "/Entitled" # the subpath of your site, e.g. /blog
# url: "https://entitledlondon.github.io/Entitled/" # the base hostname & protocol
#url: "http://localhost.com:4000/Entitled/" # the base hostname & protocol

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.entitledlondon.ca" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: EntitledLondon
github_username:  EntitledLondon

# Build settings
markdown: kramdown
#theme: alembic-jekyll-theme
remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-maps
  - jekyll-remote-theme

# Exclude from processing.
# The following items wilbul not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#3333FF"
  facebook: "#3B5998"
  Instagram: "#3B5998"

maps:
    google:
        api_key: AIzaSyDsAJ8wqvCJqpyAS6SHuDBg0kZ_bncoTBE

location:
  latitude: 42.995028
  longitude: -81.252833

google_analytics: 'UA-120910293-1'
